version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mayur211065
      MYSQL_DATABASE: journal_app
    volumes:
      - ./mysql-config/my_custom.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - app-network


  frontend:    
    build: 
      context: ./Client/frontend
      dockerfile: dockerfile
    ports:
      - "8090:3000"
    depends_on:
      - backend
    networks:
      - app-network
    
  backend:
    build: 
      context: ./Server
      dockerfile: dockerfile
    ports:
      - "5001:5001"
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Mayur211065
      - MYSQL_DB=journal_app
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge